# Generated by Django 4.1.7 on 2023-03-24 14:31

from django.db import migrations, models
from django.utils import timezone


# ------------- status field in Category model ----------------

def transfer_data_to_new_design_of_category_model(apps, schema_editor):
    Category = apps.get_model('blog', 'Category')
    for category in Category.objects.all():
        category.new_status = 'p'
        category.updated = category.published
        category.published = timezone.now()
        category.save()


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_alter_article_author_alter_article_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='created',
            new_name='published',
        ),
        migrations.AddField(
            model_name='category',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('d', 'draft'), ('p', 'publish')], default='d', max_length=1),
        ),
        migrations.RunPython(
            code=transfer_data_to_new_design_of_category_model,
            reverse_code=migrations.RunPython.noop
        ),
    ]
