# Generated by Django 4.1.7 on 2023-03-24 14:01

import django.db.models.deletion
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import migrations, models


def create_categories_from_article_categories_name(apps, schema_editor):
    Category = apps.get_model('blog', 'Category')
    Article = apps.get_model('blog', 'Article')
    for article in Article.objects.all():
        category, created = Category.objects.get_or_create(title__iexact=article.category)
        if category:
            article.new_category_id = category.id
            category.title = article.category
            category.status = True
            category.created = article.created
            category.save()
        else:
            article.category_id = None
        article.save()


def add_author_obj_to_article_from_author_name(apps, schema_editor):
    User = get_user_model()
    Article = apps.get_model('blog', 'Article')
    for article in Article.objects.all():
        author = User.objects.filter(username__iexact=article.author).first()
        article.new_author_id = author.id
        article.save()


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        # categories creation
        migrations.AddField(
            model_name='article',
            name='new_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.category'),
        ),
        migrations.RunPython(
            create_categories_from_article_categories_name,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='new_category',
            new_name='category',
        ),
        # author field reformat
        migrations.AddField(
            model_name='article',
            name='new_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(
            code=add_author_obj_to_article_from_author_name,
            reverse_code=migrations.RunPython.noop
        ),
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.AlterField(
            model_name='article',
            name='new_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.RenameField(
            model_name='article',
            old_name='new_author',
            new_name='author',
        ),
    ]
