# Generated by Django 4.1.7 on 2023-03-24 14:01
import django.db.models.deletion
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import migrations, models
from django.utils import timezone
from freezegun import freeze_time


def update_articles_and_create_categories(apps, schema_editor):
    Category = apps.get_model('blog', 'Category')
    Article = apps.get_model('blog', 'Article')
    for article in Article.objects.all():
        category, _ = Category.objects.get_or_create(
            title__iexact=article.category,
            defaults={
                'status': True,
                'title': article.category
            }
        )
        article.new_category_id = category.id
        article.save()


def update_articles_with_author_objects(apps, schema_editor):
    User = get_user_model()
    Article = apps.get_model('blog', 'Article')
    for article in Article.objects.all():
        author = User.objects.filter(username__iexact=article.author).first()
        article.new_author_id = author.id

        article.save()


def update_new_fields(apps, schema_editor):
    Article = apps.get_model('blog', 'Article')
    for article in Article.objects.all():
        with freeze_time(article.created):
            article.published = article.created
            article.updated = article.created
            article.status = 'p'
            article.save()


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        # categories creation
        migrations.AddField(
            model_name='article',
            name='new_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.category'),
        ),
        migrations.RunPython(
            update_articles_and_create_categories,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='new_category',
            new_name='category',
        ),
        # update author fieldt
        migrations.AddField(
            model_name='article',
            name='new_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(
            code=update_articles_with_author_objects,
            reverse_code=migrations.RunPython.noop
        ),
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.AlterField(
            model_name='article',
            name='new_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.RenameField(
            model_name='article',
            old_name='new_author',
            new_name='author',
        ),
        # new fields (status, published, updated)
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('d', 'draft'), ('p', 'published')], default='d', max_length=1),
        ),
        migrations.AddField(
            model_name='article',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='article',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RunPython(
            code=update_new_fields,
            reverse_code=migrations.RunPython.noop
        ),

    ]
